name: CIğŸ±
on:
 pull_request:
jobs:
  build:
    runs-on: macos-14

    name: Run Test
    steps:
      - uses: actions/checkout@v3
      - run: sudo xcode-select -s '/Applications/Xcode_15.3.app/Contents/Developer'
      - run: xcodebuild -version

